version: '3'

services:
  nginx:
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
    depends_on:
      - client
      - api

  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - NODE_ENV=development

  worker:
    build:
      context: worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - redis

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - NODE_ENV=development
      - PGHOST=postgres
      - PGUSER=user
      - PGPASSWORD=user
      - PGDATABASE=fib
      - redisHost=redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=fib

  redis:
    image: redis:5.0-alpine
